version: "3.8"

services:

  app:
    #    image: accuting
    build:
      context: .
      dockerfile: Dockerfile-linux
    restart: on-failure

    depends_on:
      - api-database4
    links:
      - api-database4
    ports:
      - 8080:8080
    env_file:
      - linux.env
    environment:
      - SERVER_PORT=8080
      #      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=$APP_NAME
      #      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      #      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
      #      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
    networks:
      - shared-net
  #    stdin_open: true
  #    tty: true
  api-database4:
    image: mongo:4.4.18
    container_name: api-database4
    hostname: api-database4
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - linux.env
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    environment:
      #      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      #      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
#      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
#      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD

    networks:
      - shared-net
#    command: ["--bind_ip","0.0.0.0"]

networks:
  shared-net:
    driver: bridge
