FROM openjdk:17-oracle
MAINTAINER RECLOY
COPY target/recloy-0.0.1.jar /recloy-0.0.1.jar
# update sources
#RUN apt-get update
## install some packages
#RUN apt-get install -y curl
#RUN mkdir -p ${MONGO_DATA_HOST_PATH}
#RUN mkdir -p ${MONGO_LOG_HOST_PATH}
#RUN mkdir -p ${MONGO_INITDB_SCRIPTS_HOST_PATH}
EXPOSE 8080
#ENTRYPOINT ["java","-Dspring.data.mongodb.uri=mongodb://api-database4:27017/recloy","-Djava.security.egd=file:/dev/./urandom","-jar","/recloy-0.0.1.jar"]
ENTRYPOINT ["java","-jar","/recloy-0.0.1.jar"]